imported code for squisher from CM
Conflicts:
	tools/squisher

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -3,14 +3,12 @@
 # Squish a Vanir otapackage for distribution
 # credit for original version: CM
 #
-
-export ANDROID_BUILD_TOP=$ANDROID_BUILD_TOP
-
 . $ANDROID_BUILD_TOP/vendor/vanir/tools/functions
 
+
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-    echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
-    exit 1
+	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+	exit 1
 fi
 
 OTAPACKAGE=$OTA_PACKAGE_PATH
@@ -20,33 +18,43 @@ if [ ! -f "$OTAPACKAGE" ]; then
     exit 1
 fi
 
+OPTICHARGER=$ANDROID_BUILD_TOP/vendor/vanir/tools/opticharger
 QUIET=-q
+DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
 REPACK=$OUT/repack.d
-printf "Sanitizing environment..."
+echo -e "Sanitizing Environment..."
 rm -rf $REPACK
 mkdir -p $REPACK
-echo
+echo -e
 
 # Unpack the otapackage and opticharge all apks
 mkdir $REPACK/ota
 (
 cd $REPACK/ota
-printf "Unpacking $OTAPACKAGE..."
+echo -e "Unpacking $OTAPACKAGE..."
 unzip $QUIET $OTAPACKAGE
-ln -s  $OUT/data $REPACK/ota/data
-echo
+echo -e
 
 # Move all apks to the same directory so xargs can
 # use also with framework-res.apk. This allow process
 # framework-res.apk in parallel with other apks
 mkdir -p $REPACK/parallel
 cd $REPACK/parallel
-find $REPACK/ota/system -name '*.apk' | while read APK; do
-    ln -s $APK .
-done
+cp $REPACK/ota/system/framework/framework-res.apk .
+cp $REPACK/ota/system/app/*.apk .
 
-find ./ -name \*.apk | $HALFXARGS schedtool -B -n 1 -e ionice -n 1 $OPTICHARGER
+# Do optimization in parallel
+find ./ -name \*.apk | $XARGS $OPTICHARGER
+
+# Move optimized apks to repack directory
+mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
+mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/
+
+# Optimize /priv-app/
+cp $REPACK/ota/system/priv-app/*.apk .
+find ./ -name \*.apk | $XARGS $OPTICHARGER
+mv -f $REPACK/parallel/*.apk $REPACK/ota/system/priv-app/
 
 # Return to directory
 cd $REPACK/ota
@@ -56,23 +64,24 @@ rm -rf $REPACK/parallel
 # move utilities
 [ -e $OUT/utilities ] && cp $OUT/utilities/* $REPACK/ota/system/xbin/
 
+
 # Determine what to name the new signed package
-MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $OUT/system/build.prop`
+MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
 OUTVERSION="$TARGET_PRODUCT"_"$MODVERSION"
 OUTFILE=$OUT/$OUTVERSION.zip
 
 # Pack it up and sign
-printf "Zipping package..."
+echo -e "Zipping package..."
 ( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
-echo
-printf "Signing package..."
+echo -e
+echo -e "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
-java -Xmx2048m \
-    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
-    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-    $REPACK/update.zip $OUTFILE
-echo
-printf "Cleaning up..."
+java -Xmx1024m \
+	-jar $OUT/../../../host/$OUT_TARGET_HOST/framework/signapk.jar \
+	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+	$REPACK/update.zip $OUTFILE
+echo -e
+echo -e "Cleaning up..."
 rm -rf $REPACK
 echo
 
