imported code for squisher from CM

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -3,14 +3,12 @@
 # Squish a Vanir otapackage for distribution
 # credit for original version: CM
 #
-
-export ANDROID_BUILD_TOP=$ANDROID_BUILD_TOP
-
 . $ANDROID_BUILD_TOP/vendor/vanir/tools/functions
 
+
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-    echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
-    exit 1
+	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+	exit 1
 fi
 
 OTAPACKAGE=$OTA_PACKAGE_PATH
@@ -20,62 +18,43 @@ if [ ! -f "$OTAPACKAGE" ]; then
     exit 1
 fi
 
+OPTICHARGER=$ANDROID_BUILD_TOP/vendor/vanir/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
-# Some products want a squashfs for xbin for space
-case "$TARGET_PRODUCT" in
-    cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
-    *) WANT_SQUASHFS=0 ;;
-esac
-
-if [ "$WANT_SQUASHFS" -eq 1 ]; then
-    fatal=0
-    MKSQUASHFS_VER_REQ=4
-    if type mksquashfs >/dev/null 2>&1; then
-        if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
-            echo
-            echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
-                fatal=1
-            fi
-        else
-            echo
-            echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
-            fatal=1
-        fi
-
-        if [ "$fatal" -ne 0 ]; then
-            echo
-            echo "       Unoptimized package is still available at"
-            echo "         $OTAPACKAGE"
-            exit $fatal
-        fi
-fi
-
 REPACK=$OUT/repack.d
-printf "Sanitizing environment..."
+echo -e "Sanitizing Environment..."
 rm -rf $REPACK
 mkdir -p $REPACK
-echo
+echo -e
 
 # Unpack the otapackage and opticharge all apks
 mkdir $REPACK/ota
 (
 cd $REPACK/ota
-printf "Unpacking $OTAPACKAGE..."
+echo -e "Unpacking $OTAPACKAGE..."
 unzip $QUIET $OTAPACKAGE
-ln -s  $OUT/data $REPACK/ota/data
-echo
+echo -e
 
 # Move all apks to the same directory so xargs can
 # use also with framework-res.apk. This allow process
 # framework-res.apk in parallel with other apks
 mkdir -p $REPACK/parallel
 cd $REPACK/parallel
-ln -s $REPACK/ota/system/framework/framework-res.apk .
-for x in $REPACK/ota/system/app/*.apk; do ln -s $x .; done
+cp $REPACK/ota/system/framework/framework-res.apk .
+cp $REPACK/ota/system/app/*.apk .
 
-find ./ -name \*.apk | $HALFXARGS schedtool -B -n 1 -e ionice -n 1 $OPTICHARGER
+# Do optimization in parallel
+find ./ -name \*.apk | $XARGS $OPTICHARGER
+
+# Move optimized apks to repack directory
+mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
+mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/
+
+# Optimize /priv-app/
+cp $REPACK/ota/system/priv-app/*.apk .
+find ./ -name \*.apk | $XARGS $OPTICHARGER
+mv -f $REPACK/parallel/*.apk $REPACK/ota/system/priv-app/
 
 # Return to directory
 cd $REPACK/ota
@@ -85,33 +64,6 @@ rm -rf $REPACK/parallel
 # move utilities
 [ -e $OUT/utilities ] && cp $OUT/utilities/* $REPACK/ota/system/xbin/
 
-if [ "$WANT_SQUASHFS" -eq 1 ]; then
-    squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
-    updater=$REPACK/ota/META-INF/com/google/android/updater-script
-
-    # Relocate su
-    cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
-    rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
-    mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
-    chmod -R 555 $REPACK/_xbin/*
-
-    # Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
-    # Forgive me for the regex hell here.
-    ln -s ../bin/su $REPACK/_xbin/su
-    for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
-    do
-        ln -s busybox $REPACK/_xbin/$link
-    done
-
-    # Create the squashfs with new and improved symlinkage!
-    mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
-    rm -rf $REPACK/ota/system/xbin/*
-    mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
-    chmod 444 $REPACK/ota/system/xbin/xbin.sqf
-
-    # Remove xbin stuff and fix up updater-script
-    $SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
-fi
 
 # Determine what to name the new signed package
 MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
@@ -119,17 +71,17 @@ OUTVERSION="$TARGET_PRODUCT"_"$MODVERSION"
 OUTFILE=$OUT/$OUTVERSION.zip
 
 # Pack it up and sign
-printf "Zipping package..."
+echo -e "Zipping package..."
 ( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
-echo
-printf "Signing package..."
+echo -e
+echo -e "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
-java -Xmx2048m \
-    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
-    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-    $REPACK/update.zip $OUTFILE
-echo
-printf "Cleaning up..."
+java -Xmx1024m \
+	-jar $OUT/../../../host/$OUT_TARGET_HOST/framework/signapk.jar \
+	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+	$REPACK/update.zip $OUTFILE
+echo -e
+echo -e "Cleaning up..."
 rm -rf $REPACK
 echo
 
