fixed squisher for nozomi

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -3,12 +3,12 @@
 # Squish a Vanir otapackage for distribution
 # credit for original version: CM
 #
+
 . $ANDROID_BUILD_TOP/vendor/vanir/tools/functions
 
-
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
-	exit 1
+    echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+    exit 1
 fi
 
 OTAPACKAGE=$OTA_PACKAGE_PATH
@@ -18,43 +18,33 @@ if [ ! -f "$OTAPACKAGE" ]; then
     exit 1
 fi
 
-OPTICHARGER=$ANDROID_BUILD_TOP/vendor/vanir/tools/opticharger
 QUIET=-q
-DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
 REPACK=$OUT/repack.d
-echo -e "Sanitizing Environment..."
+printf "Sanitizing environment..."
 rm -rf $REPACK
 mkdir -p $REPACK
-echo -e
+echo
 
 # Unpack the otapackage and opticharge all apks
 mkdir $REPACK/ota
 (
 cd $REPACK/ota
-echo -e "Unpacking $OTAPACKAGE..."
+printf "Unpacking $OTAPACKAGE..."
 unzip $QUIET $OTAPACKAGE
-echo -e
+ln -s  $OUT/data $REPACK/ota/data
+echo
 
 # Move all apks to the same directory so xargs can
 # use also with framework-res.apk. This allow process
 # framework-res.apk in parallel with other apks
 mkdir -p $REPACK/parallel
 cd $REPACK/parallel
-cp $REPACK/ota/system/framework/framework-res.apk .
-cp $REPACK/ota/system/app/*.apk .
+find $REPACK/ota/system -name '*.apk' | while read APK; do
+    ln -s $APK .
+done
 
-# Do optimization in parallel
-find ./ -name \*.apk | $XARGS $OPTICHARGER
-
-# Move optimized apks to repack directory
-mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
-mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/
-
-# Optimize /priv-app/
-cp $REPACK/ota/system/priv-app/*.apk .
-find ./ -name \*.apk | $XARGS $OPTICHARGER
-mv -f $REPACK/parallel/*.apk $REPACK/ota/system/priv-app/
+find ./ -name \*.apk | $HALFXARGS schedtool -B -n 1 -e ionice -n 1 $OPTICHARGER
 
 # Return to directory
 cd $REPACK/ota
@@ -64,24 +54,23 @@ rm -rf $REPACK/parallel
 # move utilities
 [ -e $OUT/utilities ] && cp $OUT/utilities/* $REPACK/ota/system/xbin/
 
-
 # Determine what to name the new signed package
-MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
+MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $OUT/system/build.prop`
 OUTVERSION="$TARGET_PRODUCT"_"$MODVERSION"
 OUTFILE=$OUT/$OUTVERSION.zip
 
 # Pack it up and sign
-echo -e "Zipping package..."
+printf "Zipping package..."
 ( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
-echo -e
-echo -e "Signing package..."
+echo
+printf "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
-java -Xmx1024m \
+java -Xmx2048m \
 	-jar $OUT/../../../host/$OUT_TARGET_HOST/framework/signapk.jar \
-	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-	$REPACK/update.zip $OUTFILE
-echo -e
-echo -e "Cleaning up..."
+    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+    $REPACK/update.zip $OUTFILE
+echo
+printf "Cleaning up..."
 rm -rf $REPACK
 echo
 
